---
# This playbook deploys the `cepad` module on all hosts

- hosts: all
  roles:
    - { role: prepare-node, tags: ['configuration'] }
    - { role: git-clone-module, tags: ['configuration'] }
    - { role: cepad-worker, tags: ['build'] }
